osx_image: xcode8.3
language: objective-c
podfile: Example/Podfile
before_install:
 - gem install cocoapods # Since Travis is not always on latest version
 - pod repo update
 - pod install --project-directory=Example
 - ruby rm_earlgrey_framework.rb
script:
 - set -o pipefail && xcodebuild test -workspace Example/EarlGreySnapshots.xcworkspace -scheme EarlGreySnapshots-Example -sdk iphonesimulator10.3 ONLY_ACTIVE_ARCH=NO | xcpretty
 - pod lib lint --allow-warnings
