opt_in_rules:
  - empty_count
  - sorted_imports
  - force_unwrapping
  - operator_usage_whitespace
  - number_separator
  - switch_case_on_newline
  - implicit_return
  - overridden_super_call
  - object_literal
  - nimble_operator
  - first_where
  - closure_spacing
  - closure_end_indentation
  - attributes
  - explicit_init
  - explicit_type_interface
  - fatal_error_message
  - redundant_nil_coalescing
  - private_outlet
  - conditional_returns_on_newline
  - prohibited_super_call
  - implicitly_unwrapped_optional
  - vertical_parameter_alignment_on_call
  - unneeded_parentheses_in_closure_argument
  - trailing_closure
  - single_test_class
  - quick_discouraged_call
  - pattern_matching_keywords
  - no_grouping_extension
  - no_extension_access_modifier
  - multiline_parameters
  - joined_default_parameter
  - strict_fileprivate
  - let_var_whitespace
  - extension_access_modifier
file_length:
  warning: 100
  error: 120
type_name:
  min_length: 2
  max_length:
    warning: 40
    error: 50
identifier_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
